version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: check_printer
    container_name: check_printer
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - laravel
    ports:
      - "8080:8080"   # Railway container port
    environment:
      APP_NAME: Check Printer
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: ${APP_URL}

      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}        # Railway MySQL host
      DB_PORT: ${DB_PORT}        # Railway MySQL port
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  laravel:
